- op: add
  path: /spec/storage/storageClass
  value: local-path
- op: replace
  path: /spec/storage/size
  value: 20Gi
- op: add
  path: /spec/certificates
  value:
    serverCASecret: postgres-tls-ca
    serverTLSSecret: postgres-tls
