apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: posthog-elastic
  namespace: posthog
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.17.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms512m -Xmx512m
              resources:
                requests:
                  cpu: 100m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
