apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ../posthog/namespace.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
  - https://github.com/carvel-dev/secretgen-controller/releases/download/v0.20.1/release.yml
  - https://download.elastic.co/downloads/eck/3.3.2/crds.yaml
  - https://download.elastic.co/downloads/eck/3.3.2/operator.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - altinity-clickhouse-operator.yaml
  - redpanda-operator.yaml
  - kube-prometheus-stack.yaml
